IDE_OUTPUT  = $$PWD/out
BUILD_DIR = $$_PRO_FILE_PWD_/Build
UI_DIR = $$BUILD_DIR/UI
MOC_DIR = $$BUILD_DIR/MOC
OBJECTS_DIR = $$BUILD_DIR/OBJ
IDE_LIBRARY_PATH = $$IDE_OUTPUT/libs

#message($$OBJECTS_DIR)
